# Generated by Django 5.1.4 on 2024-12-20 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainitem',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
